### ISSUE TITLE
Broken as of 3/3/2020

### ISSUE THREAD

**Issue by tiaa4c** [pikami/tiktok-dl#10]
Download for a single user is stopped somewhere before 30 videos. Tested on multiple different accounts on 2 machines and they all give less than 30 returns.

**Comment by pikami** [comment]
Thanks for reporting.
Looks like this issue is on tiktok's end, it only loads 28 videos on the browser.
[YouTube video of tiktok loading only 28 videos](https://www.youtube.com/watch?v=nGtrnfFKMC0)
Unfortunately we can't do anything, but hope that they notice this and fix it.
Leaving this issue open until something changes.

**Comment by tiaa4c** [comment]
ah yes, you're absolutely right. i had no idea a big social media site like tiktok coud have such a flaw, unless its intentional. thanks for looking into it.

**Comment by pikami** [comment]
This issue seems to be fixed
